### PR TITLE
(feat) add ability to skip field during drift evaluation for purpose of ignoring drift detection 

### PR DESCRIPTION
**Pull request by Abhi5125**
unstructured hash has patches input parameter where user can specify list of paths for drift detection to ignore; the unstructured hash function will apply a 'remove' patch to these fields and thus drift detection will compute equivalent hashes for an unstructured object even if a field changes (given that the field was chosen to be ignored)

### CODE REVIEW

**Comment by gianlucam76** [comment]
Thank you. After rebase, build is failing for one or more tests. 

Also please squash all your commits into one. As of now, you have 4 commits (and one is not yours).

The way to proceed is:

1. git checkout dev
2. git fetch upstream 
3. git merge upstream/dev
4. git checkout ignore-drift
5. git rebase -I dev

this will bring all new commits in dev to your local branch

Then squash your commits (you have 3 seperate commits in this PR) into one:

git rebase -i HEAD~3

thanks

**Comment by Abhi5125** [comment]
Closing because duplicate of #225

**Comment by Abhi5125** [comment]
Reopened because #225 is pushing to main and not dev

**Comment by kprav33n** [comment]
Review comments were taken care of and the multiple commits are now squashed into a single commit.

**Review by gianlucam76 — APPROVED** [review]
Thank you

**Pull request merged**
